# Generated by Django 6.0.1 on 2026-01-19 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='app_visitor_visited_ac3244_idx'), models.Index(fields=['path'], name='app_visitor_path_75e8b4_idx'), models.Index(fields=['ip_address'], name='app_visitor_ip_addr_f3080f_idx')],
            },
        ),
    ]
