# Generated by Django 6.0.1 on 2026-02-14 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customerprofile_decisionrecommendation_fastfoodbrand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='business_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='onboarding_date',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='total_transactions',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='trust_index',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('severity_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=255)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_delivered', models.IntegerField()),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
                ('delivery_status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('EARLY', 'Early')], max_length=20)),
                ('condition_status', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('PARTIAL', 'Partial')], max_length=20)),
                ('documentation_complete', models.BooleanField(default=True)),
                ('vehicle_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeliness_score', models.FloatField(default=0)),
                ('quantity_accuracy_score', models.FloatField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('complaint_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('risk_index', models.FloatField(default=0, help_text='Higher = more risk')),
                ('trust_index', models.FloatField(default=0, help_text='Higher = more trusted')),
                ('final_score', models.FloatField(default=0)),
                ('rating_category', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_score', models.FloatField(default=0)),
                ('flexibility_score', models.FloatField(default=0)),
                ('price_competitiveness_score', models.FloatField(default=0)),
                ('documentation_score', models.FloatField(default=0)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('DELIVERY', 'Delivery Note'), ('REVIEW', 'Review Comment'), ('COMPLAINT', 'Complaint')], max_length=20)),
                ('source_id', models.IntegerField()),
                ('text', models.TextField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='app.supplier')),
            ],
        ),
    ]
